### ISSUE TITLE
Homepage can not scrolling to the bottom

### ISSUE THREAD

**Issue by ecwu** [TerenceLiu98/terenceliu.github.io#1]
## Current Behavior
When scroll the page until Menu Sidebar appears. It will trigger a javascript function and the page will jump and go back to the position before the scroll (Where the search bar is at the bottom of the screen).

## My Environment
* Version used: Visited January 3, 2018 22:30 CST
* Environment name and version (e.g. Chrome 39, node.js 5.4): Google Chrome 63.0.3239.108 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Windows 10

**Comment by TerenceLiu98** [comment]
I will check the source code *as soon as possible*. Thank you for your advising!
